{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "inferenceProxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Files.Get "files/config.yaml" | nindent 4 }}
{{- end }}
