{{- if and .Values.proxy.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "inferenceProxy.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "inferenceProxy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "inferenceProxy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
